[build]
  base = ""
  publish = "public"
  command = "hugo --gc --themesDir ../.. -b $URL"
  publish = "exampleSite/public"

[context.production.environment]
  HUGO_VERSION = "0.74.1"

[build.environment]
  HUGO_THEME = "repo"

[context.deploy-preview]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --themesDir ../.. -b $DEPLOY_PRIME_URL"
